chore: added separate workflow

diff --git a/.github/workflows/build_to_cloudflare_pages.yml b/.github/workflows/build_to_cloudflare_pages.yml
--- a/.github/workflows/build_to_cloudflare_pages.yml
+++ b/.github/workflows/build_to_cloudflare_pages.yml
@@ -9,8 +9,10 @@ permissions:
     statuses: write
 
 on:
-    pull_request:
-        types: [opened, synchronize]
+    workflow_run:
+        workflows: ['Pre-build to Cloudflare Pages']
+        types:
+            - completed
 
 env:
     NODE_OPTIONS: '--max-old-space-size=8192'
@@ -80,8 +82,50 @@ jobs:
               id: build-project
               run: npm run build
 
-            - name: Upload build artifact
-              uses: actions/upload-artifact@v2
+            - name: Publish to Cloudflare Pages
+              id: publish-to-pages
+              env:
+                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TEST_LINKS_API_TOKEN }}
+                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_TEST_LINKS_ACCOUNT_ID }}
+              run: |
+                  echo "Installing Wrangler CLI"
+                  npm i -g wrangler
+
+                  echo "Deploying build to Cloudflare Pages"
+                  directory='public'
+                  projectName='deriv-com'
+                  branch=$GITHUB_HEAD_REF
+
+                  preview_url=$(wrangler pages deploy $directory --project-name=$projectName --branch=$branch > log.txt 2>&1; echo $?)
+                  echo "------"
+                  cat log.txt
+
+                  branchName=$(echo $branch | sed 's/[\/_]/-/g')
+                  if grep -q "Deployment complete" log.txt; then
+                    echo "preview_url=https://$branchName.deriv-com-test-links.pages.dev" > "$GITHUB_OUTPUT"
+                  else
+                    echo "Deployment to Cloudflare Pages failed."
+                    exit 1
+                  fi
+
+            - name: Retrieve Cloudflare Pages Preview URL
+              id: cloudflare_pages_preview_url
+              uses: actions/github-script@v3
               with:
-                  name: build-${{ github.head_ref }}
-                  path: .
+                  script: |
+                      const preview_url = "${{ steps.publish-to-pages.outputs.preview_url }}"
+                      const comment = [
+                        '| Name | Result |',
+                        '| :--- | :------ |',
+                        `| **Build status**  | Completed ✅ |`,
+                        `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
+                        ''
+                      ].join('\n')
+                      core.setOutput("comment", comment);
+
+            - name: Post Cloudflare Pages Preview comment
+              uses: marocchino/sticky-pull-request-comment@v2
+              with:
+                  header: Cloudflare Pages Preview Comment
+                  number: ${{github.event.issue.number}}
+                  message: ${{steps.cloudflare_pages_preview_url.outputs.comment}}
